M48
; DRILL file {KiCad 9.0.5} date 2026-05-31T10:05:32+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-31T10:05:32+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X76.67Y-108.5
X76.67Y-111.5
T2
X72.6Y-91.6
X113.4Y-91.6
M30
